controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ListeUtilisateur:

    path:       /admin/users
    controller: App\Controller\UserController::index
    methods:    [GET]

AfficheUtilisateur:

    path:       /admin/users/{id}
    controller: App\Controller\UserController::show
    methods:    [GET]

CréeUtilisateur:

    path:       /admin/users
    controller: App\Controller\UserController::create
    methods:    [POST]

ModifierUtilisateur:

    path:       /admin/users/{id}
    controller: App\Controller\UserController::update
    methods:    [PUT]    

SupprimerUtilisateur:

    path:       /admin/users/{id}
    controller: App\Controller\UserController::delete
    methods:    [DELETE]

api_login:
    path: /login